### PR TITLE
Simple showcase of a route scoped bean

### PR DESCRIPTION
**Pull request by kumm**
Bean is owned by a parent view, and injected both in parent and child. The point is to show the same instance is injected.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4)

### CODE REVIEW

**Review by mehdi-vaadin — CHANGES_REQUESTED** [review]
IMO, separating different types of classes into different packages makes the tutorial easier to understand. For example, we can have `view` and `bean` packages.

> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4#-:-LLYeQTkCVNDH78t6UVF:b3iwayb)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @kumm and @mehdi-vaadin)

___
*[src/main/java/org/vaadin/cdi/tutorial/ParentView.java, line 59 at r1](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4#-LLYcr04CUoIXHczD51t:-LLYcr04CUoIXHczD51u:bfvducy) ([raw file](https://github.com/vaadin/flow-cdi-tutorial/blob/f41665269d09db2c014deb3b44f77016cf0663fc/src/main/java/org/vaadin/cdi/tutorial/ParentView.java#L59)):*
> ```Java
>         containerStyle.set("margin", "10px");
>         add(container);
> ```

I think a link to the root should be added here to allow navigating to another route scope and back to see the behavior of `NormalRouteScoped` when we leave the scope.
___
*[src/main/java/org/vaadin/cdi/tutorial/RouteGreeter.java, line 1 at r1](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4#-LLYdsv782cXXpH42WnD:-LLYdsv782cXXpH42WnE:b4iix7i) ([raw file](https://github.com/vaadin/flow-cdi-tutorial/blob/f41665269d09db2c014deb3b44f77016cf0663fc/src/main/java/org/vaadin/cdi/tutorial/RouteGreeter.java#L1)):*
> ```
> org.vaadin.cdi.tutorial
> ```
Maybe putting the beans in another package e.g. `bean` makes the tutorial classes easier to follow.
___
*[src/main/java/org/vaadin/cdi/tutorial/RouteGreeter.java, line 9 at r1](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4#-LLYbQLa46WTI9gv4XtA:-LLYbQLa46WTI9gv4XtB:b3trjor) ([raw file](https://github.com/vaadin/flow-cdi-tutorial/blob/f41665269d09db2c014deb3b44f77016cf0663fc/src/main/java/org/vaadin/cdi/tutorial/RouteGreeter.java#L9)):*
> ```
> @RouteScopeOwner(ParentView.class)
> ```
It may be better to remove this redundant line to show that a `RouteScoped` class can be used for different owners and it's not mandatory to define a fixed owner.
___
*[src/main/java/org/vaadin/cdi/tutorial/UiGreeter.java, line 23 at r1](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4#-LLYVVC9-sqee9qPRwjP:-LLYVVC9-sqee9qPRwjQ:byyo65c) ([raw file](https://github.com/vaadin/flow-cdi-tutorial/blob/f41665269d09db2c014deb3b44f77016cf0663fc/src/main/java/org/vaadin/cdi/tutorial/UiGreeter.java#L23)):*
> ```
> UiGreeter
> ```
IMO, `UIGreeter` is better. Not blocking

**Review by kumm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @kumm and @mehdi-vaadin)

___
*[src/main/java/org/vaadin/cdi/tutorial/RouteGreeter.java, line 9 at r1](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4#-LLYbQLa46WTI9gv4XtA:-LL_o_ki-ewWqd865zX1:bjil58v) ([raw file](https://github.com/vaadin/flow-cdi-tutorial/blob/f41665269d09db2c014deb3b44f77016cf0663fc/src/main/java/org/vaadin/cdi/tutorial/RouteGreeter.java#L9)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> @RouteScopeOwner(ParentView.class)
> ```
It may be better to remove this redundant line to show that a `RouteScoped` class can be used for different owners and it's not mandatory to define a fixed owner.
</blockquote></details>

Owner for a `RouteScoped` class is mandatory, unless it is a router component - in this case omitting owner means the component is owner of self -. 
Per javadoc "Until owner remains active, all beans owned by it remain in the scope."
According to the current concept we need an owner to control the bean's lifespan.

It is redundant, because it is a CDI qualifier. You have to define it on the injection point too. This is how CDI works.

I thought about to use a normal annotation instead of a qualifier. In this case it would not be necessary at the injection point. Cons:
- it would require implement support for producers, now provided out of the box
- it would make impossible to have multiple beans with different owner, and same type

The idea is based on Delataspike's ```GroupedConversationScoped```. https://deltaspike.apache.org/documentation/jsf.html#(Grouped-)Conversations

Can you describe  the behaviour of an owner-less bean?

**Review by mehdi-vaadin — APPROVED** [review]
:lgtm:

> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4#-:-LLcZx8PAVp9rrFgiIZG:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @mehdi-vaadin and @kumm)

___
*[src/main/java/org/vaadin/cdi/tutorial/ParentView.java, line 59 at r1](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4#-LLYcr04CUoIXHczD51t:-LLcZXRo-mpHKyx0vgNX:bebrt1w) ([raw file](https://github.com/vaadin/flow-cdi-tutorial/blob/f41665269d09db2c014deb3b44f77016cf0663fc/src/main/java/org/vaadin/cdi/tutorial/ParentView.java#L59)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

I think a link to the root should be added here to allow navigating to another route scope and back to see the behavior of `NormalRouteScoped` when we leave the scope.
</blockquote></details>

Will do
___
*[src/main/java/org/vaadin/cdi/tutorial/RouteGreeter.java, line 9 at r1](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4#-LLYbQLa46WTI9gv4XtA:-LLcZexX6sM0e5s4c-Fy:b-ud7fl7) ([raw file](https://github.com/vaadin/flow-cdi-tutorial/blob/f41665269d09db2c014deb3b44f77016cf0663fc/src/main/java/org/vaadin/cdi/tutorial/RouteGreeter.java#L9)):*
<details><summary><i>Previously, kumm wrote…</i></summary><blockquote>

Owner for a `RouteScoped` class is mandatory, unless it is a router component - in this case omitting owner means the component is owner of self -. 
Per javadoc "Until owner remains active, all beans owned by it remain in the scope."
According to the current concept we need an owner to control the bean's lifespan.

It is redundant, because it is a CDI qualifier. You have to define it on the injection point too. This is how CDI works.

I thought about to use a normal annotation instead of a qualifier. In this case it would not be necessary at the injection point. Cons:
- it would require implement support for producers, now provided out of the box
- it would make impossible to have multiple beans with different owner, and same type

The idea is based on Delataspike's ```GroupedConversationScoped```. https://deltaspike.apache.org/documentation/jsf.html#(Grouped-)Conversations

Can you describe  the behaviour of an owner-less bean? 
</blockquote></details>

Got it. It was my misunderstanding. Thanks for the explanation.
___
*[src/main/java/org/vaadin/cdi/tutorial/UiGreeter.java, line 23 at r1](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4#-LLYVVC9-sqee9qPRwjP:-LLcZt9VDOYB3YcTDdgf:bebrt1w) ([raw file](https://github.com/vaadin/flow-cdi-tutorial/blob/f41665269d09db2c014deb3b44f77016cf0663fc/src/main/java/org/vaadin/cdi/tutorial/UiGreeter.java#L23)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> UiGreeter
> ```
IMO, `UIGreeter` is better. Not blocking
</blockquote></details>

Will do

**Review by mehdi-vaadin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4)* status: all files reviewed, 1 unresolved discussion (waiting on @mehdi-vaadin)

___
*[src/main/java/org/vaadin/cdi/tutorial/RouteGreeter.java, line 1 at r1](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4#-LLYdsv782cXXpH42WnD:-LLc_jtR9pk7BoTHKdN-:bebrt1w) ([raw file](https://github.com/vaadin/flow-cdi-tutorial/blob/f41665269d09db2c014deb3b44f77016cf0663fc/src/main/java/org/vaadin/cdi/tutorial/RouteGreeter.java#L1)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> org.vaadin.cdi.tutorial
> ```
Maybe putting the beans in another package e.g. `bean` makes the tutorial classes easier to follow.
</blockquote></details>

Will do

**Review by mehdi-vaadin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
