### PR TITLE
Conversion of flow-spring-tutorial to CDI

### PR DESCRIPTION
**Pull request by kumm**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/3)

### CODE REVIEW

**Review by denis-anisimov — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/3)* status: all files reviewed, 6 unresolved discussions (waiting on @vaadin-bot and @denis-anisimov)

*[a discussion](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/3#-LJeGu6Z74H8l8d_Pj29:-LJeGu6Z74H8l8d_Pj2A:b-pwrijf) (no related file):*
It might be it makes sense to add an example for `RouteScoped` beans since this is important addition to Spring scopes.

---
___
*[src/main/java/org/vaadin/cdi/tutorial/ExampleTemplate.java, line 36 at r1](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/3#-LJeGI6T4fq1qzltUd8z:-LJeGI6T4fq1qzltUd9-:b-phjjdz) ([raw file](https://github.com/vaadin/flow-cdi-tutorial/blob/7a813711f1f6ad2a8603eeff057b3375cd3be4ee/src/main/java/org/vaadin/cdi/tutorial/ExampleTemplate.java#L36)):*
> ```
> static 
> ```


extra

**Review by kumm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/3)* status: 10 of 11 files reviewed, 6 unresolved discussions (waiting on @denis-anisimov and @vaadin-bot)

___
*[src/main/java/org/vaadin/cdi/tutorial/ExampleTemplate.java, line 36 at r1](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/3#-LJeGI6T4fq1qzltUd8z:-LJoaegu0FJFVbALJZDV:b-79xke4) ([raw file](https://github.com/vaadin/flow-cdi-tutorial/blob/7a813711f1f6ad2a8603eeff057b3375cd3be4ee/src/main/java/org/vaadin/cdi/tutorial/ExampleTemplate.java#L36)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> static 
> ```


extra
</blockquote></details>

By a mass copy. Extra in spring tutorial too.

**Review by kumm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/3)* status: 10 of 11 files reviewed, 6 unresolved discussions (waiting on @denis-anisimov and @vaadin-bot)

*[a discussion](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/3#-LJeGu6Z74H8l8d_Pj29:-LJohmwY6p9pF2QDgXbD:b-bthyyt) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It might be it makes sense to add an example for `RouteScoped` beans since this is important addition to Spring scopes.
</blockquote></details>

Indeed, it should be showcased. A parent and child view, with a `RouteScoped` hello bean owned by the parent would show the point. Let it be a next PR, or push it here?

---

**Review by denis-anisimov — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/3)* status: all files reviewed, 4 unresolved discussions (waiting on @vaadin-bot)

*[a discussion](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/3#-LJeGu6Z74H8l8d_Pj29:-LJqzbQ66GSI0Te-518c:b-wm9ln9) (no related file):*
<details><summary><i>Previously, kumm wrote…</i></summary><blockquote>

Indeed, it should be showcased. A parent and child view, with a `RouteScoped` hello bean owned by the parent would show the point. Let it be a next PR, or push it here?
</blockquote></details>

OK, let's make another PR.

---

**Review by denis-anisimov — APPROVED** [review]
> Dismissed @vaadin-bot from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow-cdi-tutorial/3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
